CREATE TABLE deck_card_connection(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    deck_id INTEGER references decks(deck_id),
    card_id integer references cards(card_id),
    users integer references users(id),
    active Boolean default true
);
